config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/about'
  # get 'home/index'
  post '/' => 'home#index'
  root 'home#index'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController #HomeControler inherits ApplicationConttroller.
  def index
  	
  	if params[:id]==""
  		@nothing = "Please type in the stock!"
	elsif 

		if params[:id]
			begin
				@stock = StockQuote::Stock.quote(params[:id])	
			rescue StandardError
				@errorl = "That stock symbol doesn't exist... pleasy try again."	
			end
		end		

  		# @stock = StockQuote::Stock.quote(params[:id])
  	end

  end

  def about
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% flash.each do |name,msg| %>
	<div class="alert alert-warning alert-dismissible">
		<button class="close" data-dismiss="alert">
			<i class="glyphicons glyphicons-remove-circle"></i>
		</button>
		<%= content_tag(:div, msg) %>
	</div>
<% end %>	

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "TatarNotesAboutStocks", root_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "About us", home_about_path %></li>
      	<li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
      	<li> <%= link_to "Edit user ", edit_user_registration_path %> </li>
      	<li> <%= link_to "Log Out ", destroy_user_session_path, method: :delete %> </li>
      <% else %>
      	<li> <%= link_to "Sign up", new_user_registration_path %> </li>
      	<li> <%= link_to "Log In ", new_user_session_path %> </li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!--type in console rake route to define the link +add _path to it. create partials (_navbar.html.erb) do <render 'home/'filename'> !create filename with underscore -->

app/views/home/about.html.erb
<h1>Home#about</h1>
<p>Find me in app/views/home/about.html.erb</p>

app/views/home/index.html.erb
<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'id', nil, placeholder: 'Enter company ticket symbol', size: 50 %>
	<%= submit_tag 'Search Stock' %>
<% end %>

<br/><br/>

<% if @stock %>
	<STRONG>Company name: </STRONG> <%= @stock.name %> - <%= @stock.symbol %> <br/>
	<STRONG>Current Ask:</STRONG> <%= @stock.l %> <br/>
	<STRONG>Earnings per share </STRONG> <%= @stock.eps %> <br/>
	<STRONG>Price/Earning Ratio </STRONG> <%= @stock.pe %> <br/>
	<STRONG>Market cap </STRONG> <%= @stock.mc %> <br/>
	<STRONG>Open </STRONG> <%= @stock.op %> <br/>
	<STRONG>Day's range </STRONG> <%= @stock.lo %> - <%= @stock.hi %>  <br/>
	<STRONG>Year's high</STRONG> <%= @stock.hi52 %> <br/>
	<STRONG>Year's low</STRONG> <%= @stock.lo52 %> <br/>
	<STRONG>Summary: </STRONG> <%= @stock.summary %> <br/>
	
<% elsif @nothing %>
	<%= @nothing %>
<% elsif @errorl %>
	<%= @errorl %>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TatarStockNotes</title>
    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=3">
  </head>

  <body>

  	<%= render 'home/navbar' %>
  	
    <div class="container">
    	<%= render "home/flash" %>
    	<%= yield %>
  		
	</div>

 
  </body>

</html>